"""Lineage contract: the plan's numbers, Cypher = Python oracle, goldens, template lint.

The numbers asserted here are the ones PLAN 7.3 / 6.6 pin for the renewal model at 3efe31a.
They are typed in this test on purpose (a second, independent statement of the contract);
the committed golden file itself is generated by the oracle.
"""
from __future__ import annotations

import importlib.util
import json
import re
import shutil

import pytest
from conftest import REPO, run_script
from test_lineage_build import core_build  # noqa: F401 (session fixture shared by the lineage tests)
from test_lineage_extract import LEAKY_EDITS, UNMODELLED_EDITS, edited_sql, fake_repo

from lakehouse_graph import manifest as mf
from lakehouse_graph import spec as gspec
from lakehouse_graph.lineage import build as lbuild
from lakehouse_graph.lineage import oracle, queries, spec, tools

GOLD = "gold.churn_renewal_features."
FORBIDDEN = re.compile(r"\bINSTALL\b|\bLOAD\s+EXTENSION\b|\bLOAD\s+FROM\b|\bATTACH\b|\bEXPORT\s+DATABASE\b",
                       re.IGNORECASE)


@pytest.fixture(scope="module")
def values(core_build) -> dict:  # noqa: F811 (the imported fixture)
    return oracle.compute(oracle.load_tables(core_build[0]))


# --------------------------------------------------------------------------- the plan's numbers
def test_all_30_gold_sql_columns_resolve(values):
    g = values["gold_columns"]
    assert (g["sql_columns"], g["resolved"], g["unresolved"], g["added_by_job"]) == (30, 30, [], ["built_at"])
    assert [r["name"] for r in g["rows"]][:3] == ["user_id", "user_name", "plan_tier"] and len(g["rows"]) == 31


def test_20_of_22_features_compliant_and_exactly_two_declared_exceptions(values):
    pit = {r["feature"]: r for r in values["pit"]}
    assert len(pit) == 22 and list(pit) == list(gspec.GOLD_FEATURES)
    exceptions = {f: r for f, r in pit.items() if r["pit_status"] != "compliant"}
    assert sorted(exceptions) == ["first_renewal_after_pricing_change", "renewals_completed"]
    assert all(r["pit_status"] == "declared_exception" and r["max_upper_vs_as_of_days"] == 7
               for r in exceptions.values())
    assert exceptions["renewals_completed"]["windows"] == ["(-inf, as_of+7)"]          # latent: < renewal_date
    assert exceptions["first_renewal_after_pricing_change"]["windows"] == ["[as_of-23, as_of+7)"]
    assert pit["limit_hits_14d"]["windows"] == ["(as_of-14, as_of]"]
    assert pit["accept_rate_change"]["windows"] == ["(as_of-28, as_of]", "(as_of-56, as_of-28]"]
    assert all(not r["reads_after_as_of"] and r["max_upper_vs_as_of_days"] == 0
               for f, r in pit.items() if f not in exceptions)
    assert {f: r["pit_status"] for f, r in pit.items()} == {f: c["pit_status"] for f, c in gspec.FEATURE_CARDS.items()}


def test_pit_status_is_recomputed_from_the_edge_windows(core_build, values):  # noqa: F811
    """The stored pit_status is not taken on trust: the oracle derives it again from the
    DERIVED_FROM / COUNTS_ROWS_OF windows, and range guarantees / parameter consistency from their inputs."""
    derived = {r["feature"]: r for r in values["pit_derivation"]}
    assert list(derived) == list(gspec.GOLD_FEATURES)
    for row in values["pit"]:
        d = derived[row["feature"]]
        assert (d["pit_status"], d["max_upper_vs_as_of_days"], d["reads_after_as_of"]) == \
            (row["pit_status"], row["max_upper_vs_as_of_days"], row["reads_after_as_of"]), row["feature"]
    assert derived["renewals_completed"]["windows"] == ["(-inf, as_of+7)"]
    assert derived["incident_exposed_28d"]["windows"] == ["(as_of-28, as_of]", "unbounded"]
    assert derived["limit_hits_14d"]["reads"] == 4          # COUNT(*) + join key + window bound + the as-of anchor
    t = oracle.load_tables(core_build[0])
    assert oracle.derivation_mismatches(t) == []
    # a stored value that no longer follows from the edges is reported
    gold = spec.column_id(spec.GOLD_TABLE, "renewals_completed")
    t.nodes[gold]["pit_status"] = spec.PIT_COMPLIANT
    t.nodes[spec.column_id(spec.GOLD_TABLE, "active_days_7d")]["range_guarantee"] = "data_dependent"
    t.nodes["param:cap_cut"]["pandas_value"] = 0.8
    found = oracle.derivation_mismatches(t)
    assert len(found) == 3 and "renewals_completed: stored pit_status 'compliant'" in found[0]
    assert "active_days_7d: stored range_guarantee 'data_dependent', recomputed 'window_length(7d)'" in found[1]
    assert "parameter cap_cut: stored consistent True" in found[2]
    # ... and so is an edge window that moved without the stored status following it
    t = oracle.load_tables(core_build[0])
    edge = next(e for e in t.out("COUNTS_ROWS_OF", spec.column_id(spec.GOLD_TABLE, "limit_hits_14d")))
    edge["window"] = "(as_of-14, as_of+3]"
    assert any("limit_hits_14d: stored pit_status 'compliant', recomputed from the edge windows "
               "'undeclared_exception'" in m for m in oracle.derivation_mismatches(t))


def test_counts_rows_of_fills_the_count_star_gap(values):
    churn = {r["column"].removeprefix(GOLD): (r["dataset"], r["window"]) for r in values["counts_rows_of"]
             if r["column"].startswith(GOLD)}
    assert churn == {"renewals_completed": ("silver.churn_invoices", "(-inf, as_of+7)"),
                     "limit_hits_14d": ("silver.churn_limit_events", "(as_of-14, as_of]"),
                     "support_tickets_90d": ("silver.churn_support_tickets", "(as_of-90, as_of]")}
    assert len(values["counts_rows_of"]) == 4   # + retail gold.daily_order_metrics.orders


def test_churn_gold_sub_graph_counts(values):
    assert values["subgraph"] == {
        "gold_derived_from_edges": 137, "gold_counts_rows_of_edges": 3, "distinct_silver_columns_read": 38,
        "window_usage": {"(as_of-28, as_of]": 29, "all history (no time filter)": 12, "(-inf, as_of]": 4,
                         "(as_of-56, as_of-28]": 3, "(as_of-7, as_of]": 2, "(as_of-14, as_of]": 2,
                         "(as_of-90, as_of]": 2, "(-inf, as_of+7)": 2, "[as_of-23, as_of+7)": 1}}


def test_the_9_silver_columns_gold_never_reads(values):
    data = values["questions"]["Q17_unused_silver"]["data"]
    assert data["columns"] == [
        "silver.churn_incidents.incident_id", "silver.churn_invoices.amount_usd", "silver.churn_invoices.attempt",
        "silver.churn_limit_events.hit_at", "silver.churn_limit_events.limit_type",
        "silver.churn_pricing_changes.change_id", "silver.churn_pricing_changes.description",
        "silver.churn_subscription_snapshots.status", "silver.churn_support_tickets.ticket_id"]
    assert data["summary"] == {"columns": 47, "unused": 9} and data["read_by"] == "gold"
    # the business graph still reads 8 of them (status is the one nobody reads)
    assert sorted(set(data["columns"]) - set(data["also_read_by_graph"])) == [
        "silver.churn_subscription_snapshots.status"]


def test_the_4_gold_columns_with_no_value_check(values):
    data = values["questions"]["Q16_unguarded_gold"]["data"]
    assert sorted(c.removeprefix(GOLD) for c in data["unguarded"]) == ["built_at", "city", "feature_as_of",
                                                                       "renewal_date"]
    assert data["summary"] == {"columns": 31, "value_checked": 27, "unguarded": 4}


def test_6_of_18_contract_ranges_are_guaranteed_by_the_sql(values):
    r = values["range_guarantees"]
    assert (r["ranges"], r["guaranteed"]) == (18, 6)
    assert r["by_kind"]["sql_clamp"] == ["accept_rate_change", "allowance_used_pct", "engagement_trend",
                                         "last_active_days_ago"]
    assert r["by_kind"]["window_length"] == ["active_days_28d", "active_days_7d"]
    assert len(r["by_kind"]["data_dependent"]) == 12


def test_leaky_has_the_dangling_member(values):
    assert values["leaky"]["dangling"] == ["cancel_at_period_end"]
    assert "cancel_at_period_end" in values["leaky"]["declared"] and len(values["leaky"]["declared"]) == 7


def test_parameters_are_consistent(values):
    p = {x["name"]: x for x in values["parameters"]}
    assert {n: x["sql_value"] for n, x in p.items() if x["consistent"]} == {
        "allowance.pro": 550.0, "allowance.pro_plus": 1650.0, "allowance.ultra": 11000.0, "cap_cut": 0.83,
        "as_of_offset_days": 7.0}
    assert all(x["sql_value"] == x["pandas_value"] == x["generator_value"] for x in p.values() if x["consistent"])
    assert p["dunning_days"]["unused"] is True and p["dunning_days"]["consistent"] is None


def test_invariant_9_silver_hit_at_has_no_gold_descendant(values):
    inv = values["invariant_9"]
    assert inv["silver_gold_descendants"] == []
    assert inv["bronze_paths_to_gold"] == [["bronze.churn_limit_events_raw.hit_at",
                                            "silver.churn_limit_events.hit_date", GOLD + "limit_hits_14d"]]
    # ... and the two tools that answer Q15 and Q17 agree with it
    assert values["questions"]["downstream_silver_hit_at"]["data"]["reached"]["columns"] == {}
    assert "silver.churn_limit_events.hit_at" in values["questions"]["Q17_unused_silver"]["data"]["columns"]


def test_bridge_covers_all_21_business_graph_types(values):
    b = values["bridge"]
    assert (b["elements"], b["nodes"], b["edges"]) == (21, len(gspec.NODE_SCHEMA), len(gspec.EDGE_SCHEMA))
    assert {e["element"] for e in b["by_element"]} == \
        {f"ge:node:{n}" for n in gspec.NODE_SCHEMA} | {f"ge:edge:{r}" for r in gspec.EDGE_SCHEMA}
    assert all(e["datasets"] >= 1 and e["source_columns"] >= 1 and e["tables"] == 1 for e in b["by_element"])


# --------------------------------------------------------------------------- twice: Cypher = oracle
def test_every_golden_answer_is_equal_in_cypher_and_in_the_python_oracle(core_build, values):  # noqa: F811
    with tools.LineageContext(core_build[0]) as ctx:
        def answer(tool, **args):
            return tools.TOOLS[tool](ctx, **args)
        cypher = {**queries.contract_sections(ctx.lineage_conn),
                  "pit": oracle.pit_all(answer, [r["feature"] for r in values["pit"]]),
                  "questions": oracle.questions(answer)}
    assert set(cypher) == set(values)
    for key in values:
        assert oracle.diff(values[key], cypher[key]) == [], key
    assert json.dumps(cypher, sort_keys=True, default=str) == json.dumps(values, sort_keys=True, default=str)
    assert len(values["questions"]) == len(spec.QUESTIONS) + len(spec.EXTRA_QUESTIONS) and len(spec.QUESTIONS) == 7


def test_oracle_equals_the_committed_golden(core_build, values):  # noqa: F811
    doc, note, _exact = oracle.find_golden(core_build[1])
    assert doc is not None, note
    assert doc["profile"] == "core" and doc["spec"] == spec.SPEC_VERSION and doc["golden_version"] == 1
    assert oracle.diff(doc["values"], values) == []
    assert set(doc["inputs_sha256"]) <= set(spec.SEMANTIC_FILES)
    assert "reported_not_gated" in doc and "counts" not in doc["values"]   # totals are reported, never compared
    assert oracle.diff({"a": [1, {"b": 2.0}]}, {"a": [1, {"b": 2}]}) == []
    assert oracle.diff({"a": [1, 2]}, {"a": [1, 3], "c": 0}) == ["/a[1]: 3 != expected 2", "/c: unexpected"]


# --------------------------------------------------------------------------- the script
def test_contract_script_passes_strict_on_the_core_profile(core_build, tmp_path):  # noqa: F811
    bdir = tmp_path / "build"
    shutil.copytree(core_build[0], bdir)
    # a private copy, refreshed to the repo as it is now (kept when nothing changed since the session build)
    _dir, man = lbuild.build_lineage(bdir, "core", log=lambda *_: None)
    out = tmp_path / "result.json"
    p = run_script("check_lineage_contract.py", "--build", str(bdir), "--strict", "--json", str(out))
    assert p.returncode == 0, p.stdout[-3000:] + p.stderr
    assert "FAIL" not in p.stdout and "WARN" not in p.stdout
    for line in ("all 30 gold SQL output columns resolve", "20 of 22 features compliant",
                 "lineage pit_status = FEATURE_CARDS pit_status for all 22 features",
                 "stored pit_status, range_guarantee and parameter consistency = recomputed from the edge windows",
                 "pit_derivation: Cypher = oracle",
                 "invariant 9: silver.churn_limit_events.hit_at has no gold descendant",
                 "bridge: all 21 business graph types", "Q15_downstream_bronze_hit_at", "Cypher = oracle",
                 "Whole-graph totals (reported, not gated)", "lineage Cypher templates have ORDER BY"):
        assert line in p.stdout, line
    assert "Lineage contract OK (metadata-graph/0.1, profile core" in p.stdout and "; strict" in p.stdout
    doc = json.loads(out.read_text())
    assert doc["status"] == "pass" and doc["strict"] is True and doc["golden"] == "core.json"
    assert doc["lineage_build_id"] == man["lineage_build_id"]
    assert set(doc["latency_ms"]) == {k for k, *_ in spec.QUESTIONS}
    assert all(set(x) == {"best_ms", "median_ms", "max_ms"} for x in doc["latency_ms"].values())
    cold = doc["latency_cold_ms"]           # a fresh connection: reported next to the warm numbers, never gated
    assert cold["open_ms"] > 0 and list(cold["first_call_ms"]) == [k for k, *_ in spec.QUESTIONS]
    assert "cold (a fresh read-only connection, 128 MB pool): open" in p.stdout
    final = next(line for line in p.stdout.splitlines() if line.startswith("Lineage contract OK"))
    warm = max(doc["latency_ms"], key=lambda k: doc["latency_ms"][k]["median_ms"])
    first = max(cold["first_call_ms"], key=cold["first_call_ms"].get)
    assert f"; slowest question {warm} {doc['latency_ms'][warm]['median_ms']} ms (median, warm); slowest first " \
           f"call {first} {cold['first_call_ms'][first]} ms (cold, after a {cold['open_ms']} ms open)" in final, final
    record = json.loads((bdir / spec.LINEAGE_DIR / spec.CONTRACT_FILE).read_text())
    assert record["status"] == "pass" and record["files_sha256"] == {k: v["sha256"] for k, v in man["files"].items()}


def test_latency_summary_names_the_slowest_warm_question_and_the_slowest_first_call():
    mspec = importlib.util.spec_from_file_location("check_lineage_contract_under_test",
                                                   REPO / "scripts" / "check_lineage_contract.py")
    mod = importlib.util.module_from_spec(mspec)
    mspec.loader.exec_module(mod)
    warm = {"Q13": {"median_ms": 1.2}, "Q15": {"median_ms": 3.1}, "Q16": {"median_ms": 2.0}}
    cold = {"open_ms": 55.0, "first_call_ms": {"Q13": 4.0, "Q15": 14.3, "Q16": 26.9}}   # not the first question
    assert mod.latency_summary(warm, cold) == ("; slowest question Q15 3.1 ms (median, warm); slowest first call "
                                               "Q16 26.9 ms (cold, after a 55.0 ms open)")
    assert mod.latency_summary(warm, {}) == "; slowest question Q15 3.1 ms (median, warm)"
    assert mod.latency_summary({}, {}) == ""


def test_contract_script_fails_loudly_on_a_bad_build(core_build, tmp_path):  # noqa: F811
    bdir, man = core_build
    missing = run_script("check_lineage_contract.py", "--build", str(tmp_path / "nothing"))
    assert missing.returncode == 1 and "no lineage build" in missing.stderr
    # an unresolved name recorded by the extractor is a contract error, strict or not
    bad = tmp_path / "unresolved"
    shutil.copytree(bdir, bad)
    doc = dict(man, unresolved=[{"where": "Makefile:new-target", "what": "runs scripts/gone.py, which does not exist"}])
    mf.write_json_atomic(bad / spec.LINEAGE_DIR / spec.MANIFEST_FILE, doc)
    p = run_script("check_lineage_contract.py", "--build", str(bad), "--no-ladybug")
    assert p.returncode == 1 and "unresolved name: Makefile:new-target" in p.stdout
    assert json.loads((bad / spec.LINEAGE_DIR / spec.CONTRACT_FILE).read_text())["status"] == "fail"
    # a tampered Parquet table is an integrity error
    tampered = tmp_path / "tampered"
    shutil.copytree(bdir, tampered)
    victim = tampered / spec.LINEAGE_DIR / "edges_DERIVED_FROM.parquet"
    shutil.copy2(tampered / spec.LINEAGE_DIR / "edges_COUNTS_ROWS_OF.parquet", victim)
    p = run_script("check_lineage_contract.py", "--build", str(tampered), "--no-ladybug")
    assert p.returncode == 1 and "changed or missing" in p.stdout
    # --no-ladybug alone only warns (and fails under --strict)
    assert run_script("check_lineage_contract.py", "--build", str(bdir), "--no-ladybug").returncode == 0
    assert run_script("check_lineage_contract.py", "--build", str(bdir), "--no-ladybug", "--strict").returncode == 1


@pytest.mark.parametrize("name", ["case_under_not", "two_cases_take_the_loosest"])
def test_contract_fails_when_a_feature_reads_after_as_of_without_a_declaration(tmp_path, name):
    """A leaky rewrite of the gold SQL (a CASE bound under NOT; a second CASE with a looser bound) must
    fail the contract with a readable reason, and the rest of the contract must still hold on that build."""
    _feature, upper, edits = LEAKY_EDITS[name]
    root = fake_repo(tmp_path)
    (root / spec.GOLD_SQL).write_text(edited_sql(edits))
    bdir = tmp_path / "build"
    _dir, man = lbuild.build_lineage(bdir, "core", repo=root, log=lambda *_: None)
    assert man["unresolved"] == []
    p = run_script("check_lineage_contract.py", "--build", str(bdir))
    assert p.returncode == 1 and "Traceback" not in p.stderr, p.stdout[-2000:] + p.stderr[-2000:]
    fails = [line.strip() for line in p.stdout.splitlines() if "FAIL" in line]
    assert fails == [
        "FAIL  every feature is compliant or a declared exception: undeclared exception (reads after as_of, not "
        "declared in FEATURE_CARDS): ['allowance_used_pct']",
        "FAIL  lineage pit_status = FEATURE_CARDS pit_status for all 22 features: differ: ['allowance_used_pct']"]
    assert "Known conservative cases" in p.stdout and "FEATURE_CARDS; a read that is in fact bounded" in p.stdout
    # everything else still holds on the leaky build: the recomputation agrees, and Cypher = oracle for every
    # answer (two edges to one column with different windows keep a total order)
    assert "ok    stored pit_status, range_guarantee and parameter consistency = recomputed" in p.stdout
    assert "ok    upstream_allowance_used_pct" in p.stdout and "ok    pit: Cypher = oracle" in p.stdout
    with tools.LineageContext(bdir) as ctx:
        data, caveats = tools.lineage_pit(ctx)
        trace, _ = tools.lineage_trace(ctx, GOLD + "allowance_used_pct")
    assert [f["feature"] for f in data["features"]] == ["allowance_used_pct", "first_renewal_after_pricing_change",
                                                        "renewals_completed"]
    assert data["summary"]["undeclared_exception"] == 1
    pricing = sorted(e["window"] for e in trace["edges"] if e["to"] == "silver.churn_pricing_changes.effective_date")
    if upper == 7:
        assert data["features"][0]["max_upper_vs_as_of_days"] == 7 and pricing == ["(-inf, as_of+7)", "(-inf, as_of]"]
        assert any("allowance_used_pct: UNDECLARED exception; its window ends 7 day(s) after as_of "
                   "(silver.churn_pricing_changes.effective_date in (-inf, as_of+7))" in c for c in caveats)
    else:
        assert data["features"][0]["max_upper_vs_as_of_days"] is None and pricing == ["unbounded"]
        assert any("allowance_used_pct: UNDECLARED exception; it has no upper time bound" in c for c in caveats)
        assert any("silver.churn_pricing_changes (effective_date) is read without any time bound" in c
                   for c in caveats)


@pytest.mark.parametrize("name", ["renewals_window_over_all_renewals", "feature_cte_order_by_limit"])
def test_a_stopped_extraction_keeps_the_last_good_lineage(core_build, tmp_path, name):  # noqa: F811
    """The verifier's major finding end to end: a window function in the renewals CTE (and ORDER BY ... LIMIT
    in a feature CTE) no longer yields a compliant graph; the build stops before writing anything, so the
    existing lineage (and its passing contract) stays exactly as it was."""
    message, edits = UNMODELLED_EDITS[name]
    bdir = tmp_path / "build"
    shutil.copytree(core_build[0], bdir)
    before = {p.relative_to(bdir): mf.sha256_file(p) for p in sorted(bdir.rglob("*")) if p.is_file()}
    root = fake_repo(tmp_path)
    (root / spec.GOLD_SQL).write_text(edited_sql(edits))
    with pytest.raises(spec.LineageExtractError, match=message):
        lbuild.build_lineage(bdir, "core", repo=root, log=lambda *_: None)
    assert {p.relative_to(bdir): mf.sha256_file(p) for p in sorted(bdir.rglob("*")) if p.is_file()} == before
    assert not [p.name for p in bdir.iterdir() if p.name.startswith(lbuild.TMP_PREFIX)]


def test_stale_build_is_detected(core_build):  # noqa: F811
    _bdir, built = core_build
    # the manifest as it would be if built right now (other work may have touched the repo since the session build)
    man = {**built, "inputs_sha256": {rel: mf.sha256_file(REPO / rel) for rel in built["inputs_sha256"]},
           "code_sha256": lbuild.code_hashes()}
    assert lbuild.is_fresh(man)
    assert not lbuild.is_fresh({**man, "inputs_sha256": {**man["inputs_sha256"], spec.README: "0" * 64}})
    assert not lbuild.is_fresh({**man, "inputs_sha256": {**man["inputs_sha256"], "scripts/gone.py": "0" * 64}})
    assert not lbuild.is_fresh({**man, "code_sha256": {**man["code_sha256"], spec.CONTENT_CODE[0]: "0" * 64}})


# --------------------------------------------------------------------------- template lint
@pytest.mark.parametrize("name", sorted(queries.TEMPLATES))
def test_lineage_template_has_order_by_and_limit(name):
    q = queries.TEMPLATES[name]
    order = [m.start() for m in re.finditer(r"\bORDER\s+BY\b", q, re.IGNORECASE)]
    limit = [m.start() for m in re.finditer(r"\bLIMIT\b", q, re.IGNORECASE)]
    assert order and limit and order[-1] < limit[-1], f"{name} needs ORDER BY followed by LIMIT"
    assert re.search(r"\bLIMIT\s+\d+\s*$", q.rstrip().splitlines()[-1]), f"{name}: must end with a literal LIMIT"
    assert int(q.rstrip().rsplit(None, 1)[-1]) <= queries.ROW_LIMIT
    assert not re.search(r"\bUNION\b", q, re.IGNORECASE), name
    assert not re.search(r"\b(CREATE|MERGE|DELETE|SET|DROP|ALTER|COPY|CALL)\b", q, re.IGNORECASE), f"{name}: read-only"
    assert not FORBIDDEN.search(q), name
    assert "`Column`" not in q and ":Column" not in q, f"{name}: the label is DataColumn"
    unquoted = re.findall(r"\(\w*:([A-Z][A-Za-z]+)", q)
    assert not unquoted, f"{name}: node labels must be back-quoted ({unquoted})"


def test_lineage_templates_catalog_and_render():
    assert sorted(k for k in queries.TEMPLATES if k.startswith("contract_")) == queries.CONTRACT_ONLY
    assert {"trace_upstream_step", "trace_downstream_step", "pit_features", "guards_assertions",
            "unused_columns", "column_by_ref"} <= set(queries.TEMPLATES)
    assert "MATCH (n:`DataColumn`)" in queries.render("count_nodes", label="DataColumn")
    for bad in ({"label": "Column"}, {"label": "DataColumn`) DETACH DELETE (n"}, {"rel": "NOPE"}, {"table": "Job"}):
        with pytest.raises(ValueError):
            queries.render("count_rels" if "rel" in bad else "count_nodes", **bad)
